version: '3.7'

services:
  configurator_db:
    image: mysql:5.7
    command: mysqld --sql_mode="" --general-log=1 --general-log-file=/var/log/mysql/general-log.log
    container_name: configurator_db
    ports:
     - "3306:3306"
    volumes:
     - ./src/database/dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_USER: config_usr
      MYSQL_PASSWORD: changeme
      MYSQL_DATABASE: configurator
      TZ: America/Lima
    networks:
      - configurator_network
    healthcheck:
          test: "cat /var/log/mysql/general-log.log | grep \"root@localhost on  using Socket\""
          interval: 1s
          retries: 120

  configurator:
    build: .
    image: configurator
    container_name: configurator
    ports:
     - "80:2708"
    environment:
      CONFIGURATOR_DATABASE_HOST: host.docker.internal
      CONFIGURATOR_DATABASE_USER: config_usr
      CONFIGURATOR_DATABASE_PASSWORD: changeme
      CONFIGURATOR_DATABASE_PORT: 3306
      CONFIGURATOR_DATABASE_NAME: configurator
      CONFIGURATOR_API_KEY: changeme
      CONFIGURATOR_CRYPT_KEY: changeme
      CONFIGURATOR_BFA_THRESHOLD: 100
      TZ: America/Lima
    networks:
      - configurator_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
        configurator_db:
            condition: service_healthy

networks:
  configurator_network:
    driver: bridge
